name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build (package)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Upgrade pip and install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build wheel
        run: |
          python -m build --wheel
      - name: Show build artifacts
        run: ls -lah dist || true

  test:
    name: Test (pytest)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test] || true
          pip install pytest

      - name: Run tests
        run: pytest -q

  deploy:
    name: Deploy (simulado)
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Simulated deploy
        run: |
          echo "===== Simulating deploy ====="
          echo "This is a simulated deploy step. Replace with real deploy commands."
          echo "List dist artifacts (from build):"
          ls -lah dist || echo "No dist folder found in this checkout (build ran on separate job)."
          echo "If you want to persist artifacts between jobs, use actions/upload-artifact / download-artifact."
          echo "Deploy OK (simulated)."